### DISCUSSION TITLE
164. 如何设计一个通用卡片？

### DISCUSSION THREAD

**Discussion by ly525** [liuyanshi/gesang-fe-something#572] [设计｜CSS]
1. 设计一个card 通常需要哪些内容呢？
2. 做一个通用型的卡片需要了解什么？
3. 有哪些需要注意的点呢？

## 场景
最近一周做的东西，涉及到了很多的卡片：小型卡片、grid 卡片（grid 的col-12 作为一个card）
在做完第一个版本的时候，自己看了下页面的整体设计，很粗糙，感觉像是完全没有设计过一样。
于是参照了一些 material design 的card 设计和 dribble 上的卡片设计，自己这时候会有些类似职业困扰之类的东西会出现
做一个通用型的卡片，它里面包含了哪些内容呢？
怎么样才能算是一个比较通用型的卡片：
> card 的圆角、边框、展开折叠、标题（高度、字体大小、边距）、留白、卡片之间的间距等其他的一些效果的实现。

这些都算是一个card一些基础的，那么或许material design 有card的实现。说明我应该去读一下这方面的内容，这应该是我现阶段更合适的做法，没有完整的读过或者遵循一个设计规范做过一些比较成熟的组件，是非常不应该的。
希望下次再做一个card 组件的时候，能够快速整理出：一个基本的卡片内容应该去考虑哪些点，有哪些需要注意的事项等等。

```css
// .mdui-card-actions-stacked 是写在哪里的？
.mdui-card-actions-stacked .mdui-btn {
    display: block;
    margin: 0 0 4px 0;
}
```
