### DISCUSSION TITLE
less calc

### DISCUSSION THREAD

**Discussion by ly525** [liuyanshi/gesang-fe-something#586] [设计｜CSS]
```less
#designer-page {
  display: flex;
  // https://stackoverflow.com/questions/17904088/disable-less-css-overwriting-calc
  // less: 
  min-height: ~'calc(100% - 40px)';
  // scss
  min-height: calc(100% - 40px);

}
```
