### DISCUSSION TITLE
250. 日期选择器(DateRangePicker) 的  CSS 设计思路

### DISCUSSION THREAD

**Discussion by ly525** [liuyanshi/gesang-fe-something#587] [设计｜CSS]
### Questions
1. Why style scoped and what style scoped does?
2. Do I need style scoped for the date-range-picker? the advantages and disadvantages of it?

# box-sizing
1. use `box-sizing：border-box;` for input box
> without `box-sizing: border-box;`
> because the the icon is inside the input box with padding-left, so the input box is pushed to the right.

> ![box-sizing](http://jietu-10024907.file.myqcloud.com/wgmvzpfmebjmmwlcpshlqhyndpemeiza.jpg)
> ![](http://jietu-10024907.file.myqcloud.com/iyvyrrzixqywztdfmznlinqxvspgscpm.jpg)

> [Solved] add `box-sizing: border-box` for input box
> ![](http://jietu-10024907.file.myqcloud.com/ivmejgvcxobommycdqxvkjtlcoafjyab.jpg)

2. 表格组件的 rowHeight
表格的每一行都有一个1px 的border-bottom，如果不使用border-box的话，这样每次计算表格的总高度的时候，都需要用 rowHeight * rowsCount + 1px * rowCount，这样和开发者理解的rowHeight就有歧义了。而且不利于计算

```css
.table-wrapper * {
   box-sizing: border-box;

  .table-cell {
     border-bottom: 1px solid grey;
   }
}
```

# day.off
1. Items that do not belong to the current month（ 不属于当前月份的 item）
```scss
td,
th {
  &.off,
  &.off.in-range,
  &.off.start-date,
  &.off.end-date {
    background-color: #fff;
    border-color: transparent;
    color: #999;
  }
}
```
> ![](http://jietu-10024907.file.myqcloud.com/eytzbtngenkqzraihjnbjhiubefeohql.jpg)
> without `.off` style:
> ![](http://jietu-10024907.file.myqcloud.com/alvlbbhaaugfrlotdrjoxfvjlrdvosmf.jpg)

# 下拉菜单中的箭头 ⬆️生成
> ![image](https://user-images.githubusercontent.com/12668546/51485362-cd899c80-1dd8-11e9-91f2-8a18b0adcdf4.png)

# 左右布局： rtl、ltr
